language: node_js

node_js:
  "stable"

before_install:
  - npm i -g npm@6.4.1
  
cache:
  directories:
    "node_modules"

env: 
  - NODE_ENV=test
  - JWT_KEY=TheBestPassWordOnEarth9023

services:
  - postgresql

before_script:
  - psql -c "DROP DATABASE travis_ci_test;" -U postgres
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres