swagger: "2.0"
info:
  version: "1.0.0"
  title: SendIt App
host: localhost:3000
basepath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
/parcels:
  get:
    description: Returns all parcels order delivery that has been created.
    produces:
    - application/json
    responses:
      '200':
        description: A list of parcel order delivery.
        schema:
          type: array
          items:
            $ref: 